trigger:
  branches:
    include:
      - main

pool:
  name: infra-pool

variables:
  System.Debug: true
  terraformWorkingDirectory: '$(Build.SourcesDirectory)/Environment/dev'

stages:
- stage: Terraform
  displayName: Terraform Deployment

  jobs:
  - job: TerraformJob
    displayName: Terraform Job

    steps:

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.15.8'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(terraformWorkingDirectory)
        backendServiceArm: infra-svc
        backendAzureRmOverrideSubscriptionID: d4fb712a-aae3-49cf-8c1b-9ed8f8b11a56
        backendAzureRmResourceGroupName: production-rg
        backendAzureRmStorageAccountName: prodstorage1998
        backendAzureRmContainerName: container
        backendAzureRmKey: terraform-tf-state

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: $(terraformWorkingDirectory)

    - script: |
        echo ===== Terraform Version =====
        terraform version

        echo ===== Terraform Providers =====
        terraform providers

        echo ===== Current Workspace =====
        terraform workspace show
      workingDirectory: $(terraformWorkingDirectory)
      displayName: Terraform Debug

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: $(terraformWorkingDirectory)
        environmentServiceNameAzureRM: infra-svc

    - task: TerraformTask@5
      displayName: Terraform Apply
      condition: succeeded()
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: $(terraformWorkingDirectory)
        environmentServiceNameAzureRM: infra-svc