trigger:
  branches:
    include:
      - main

pool:
  name: infra-pool

variables:
  terraformWorkingDirectory: '$(Build.SourcesDirectory)/Environment/dev'

stages:
- stage: Terraform
  displayName: Terraform Deployment

  jobs:
  - job: TerraformJob
    displayName: Terraform Job

    steps:

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: latest

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(terraformWorkingDirectory)
        backendServiceArm: infra-svc
        backendAzureRmOverrideSubscriptionID: d4fb712a-aae3-49cf-8c1b-9ed8f8b11a56
        backendAzureRmResourceGroupName: production-rg
        backendAzureRmStorageAccountName: prodstorage1998
        backendAzureRmContainerName: container
        backendAzureRmKey: terraform-tf-state

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: $(terraformWorkingDirectory)

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: $(terraformWorkingDirectory)
        environmentServiceNameAzureRM: infra-svc

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: $(terraformWorkingDirectory)
        environmentServiceNameAzureRM: infra-svc